author: stevepapazis
description: >- # this means to ignore newlines until "baseurl:"
  A web portfolio
baseurl: "/web-dev" # the subpath of your site, e.g. /blog
url: "https://stevepapazis.github.io" # the base hostname & protocol for your site, e.g. http://example.com


plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - node_modules